language: node_js
node_js:
  - 7

sudo: false

cache:
  directories:
    - node_modules

before_deploy:
  - npm config set _auth $ARTIFACTORY_API_KEY
  - npm config set email $ARTIFACTORY_EMAIL

deploy:
  provider: script
  script: npm publish
  on:
    branch: master
    tags: true
